---
- block:
  - name: "Checking if the instance already exits"
    stat:
      path: "{{ instance_path }}"
    register: existing_instance_path_before
    tags: ['init','up','update','test','stop','rm']

  - set_fact: instance_exists_before="{{ existing_instance_path_before.stat.exists }}"
    tags: ['init','up','update','test','stop','rm']

  - name: Create instance
    file:
      state: directory
      path: "{{ instance_path }}"
    tags: ['init']

  - name: "Checking if the instance is exists or created"
    stat:
      path: "{{ instance_path }}"
    register: existing_instance_path
    tags: ['init','up','update','test','stop','rm']

  - set_fact: instance_exists="{{ existing_instance_path.stat.exists }}"
    tags: ['init','up','update','test','stop','rm']

  - name: Changing perm of "{{ instance_path }}"
    file: dest="{{ instance_path }}" mode=777  recurse=yes
    tags: ['update','test']
    when: instance_exists

  - name: git clone/pull
    git:
      repo: "{{ git_repository_path }}"
      dest: "{{ instance_path }}"
      version: "{{ branch }}-build"
      accept_hostkey: true
      force: yes
    tags: ['init','update','test']
    when: instance_exists

  - name: Create docksal-local.env file
    template:
      src: "templates/.docksal/docksal-local.env"
      dest: "{{ instance_path }}/.docksal/docksal-local.env"
    tags: ['init']
    when: instance_exists

  - name: Create docksal-local.yml file
    template:
      src: "templates/.docksal/docksal-local.yml"
      dest: "{{ instance_path }}/.docksal/docksal-local.yml"
    tags: ['init']
    when: instance_exists

  - name: fin up
    command: fin up
    args:
      warn: false
      chdir: "{{ instance_path }}"
    tags: ['init', 'up', 'update','test']
    when: instance_exists

  - name: Include init tasks
    include: "{{ hook_init_tasks | default(role_path  ~ '/hooks/hook_init_tasks.yml') }}"
    tags: ['init']
    when: instance_exists

  - name: "Add alias {{ alias }}"
    command: "fin alias {{ instance_path }} {{ alias }}"
    args:
      warn: false
      chdir: "{{ instance_path }}"
    tags: ['init']
    when: instance_exists

  - name: Include update tasks
    include: "{{ hook_update_tasks | default(role_path ~ '/hooks/hook_update_tasks.yml') }}"
    tags: ['init', 'update','test']
    when: instance_exists

  - debug:
      msg: "Instance {{ instance_path }} created. See: {{ instance_protocol }}://{{ instance_domain }}"
    when: instance_exists
    tags: ['init']

  - debug:
      msg: "Instance {{ instance_path }} updated. See: {{ instance_protocol }}://{{ instance_domain }}"
    when: instance_exists
    tags: ['update']

  - name: Include test tasks
    include: "{{ hook_test_tasks | default(role_path ~ '/hooks/hook_test_tasks.yml') }}"
    tags: ['test']
    when: instance_exists

  - name: fin stop
    command: fin stop
    args:
      warn: false
      chdir: "{{ instance_path }}"
    tags: ['stop', 'rm']
    ignore_errors: yes
    when: instance_exists

  - name: "Remove alias {{ alias }}"
    command: "fin alias remove {{ alias }}"
    args:
      warn: false
      chdir: "{{ instance_path }}"
    tags: ['rm']
    ignore_errors: yes
    when: instance_exists

  - name: fin rm
    command: "fin rm -f"
    args:
      warn: false
      chdir: "{{ instance_path }}"
    tags: ['rm']
    ignore_errors: yes
    when: instance_exists

  - name: Changing perm of "{{ instance_path }}"
    file: dest="{{ instance_path }}" mode=777  recurse=yes
    tags: ['rm']
    when: instance_exists

  - name: Clean instance
    file:
      state: absent
      path: "{{ instance_path }}"
    tags: ['rm']
    when: instance_exists